package com.ecarinfo.auto.rm;
public class MouthAnalyzingRM {
	public static final String tableName="mouth_analyzing";//表名
	public static final String pk="id";//主键
	public static final String id="id";//对应数据库主键,
	public static final String optionId="option_id";//原文对应id
	public static final String title="title";//
	public static final String content="content";//内容
	public static final String url="url";//
	public static final String brandId="brand_id";//厂牌ID
	public static final String serialId="serial_id";//车系id
	public static final String provinceId="province_id";//省份id
	public static final String cityId="city_id";//城市id
	public static final String mediaId="media_id";//媒体Id
	public static final String type="type";//文章分类，综合，论坛，微博等。
	public static final String affection="affection";//综合情感 1好2中3差
	public static final String points="points";//综合评价
	public static final String appearance="appearance";//外观1有，0无
	public static final String appearanceAffection="appearance_affection";//情感，1好，2中，3差
	public static final String interior="interior";//内饰 1有 0无
	public static final String interiorAffection="interior_affection";//
	public static final String space="space";//空间
	public static final String spaceAffection="space_affection";//
	public static final String operate="operate";//操控
	public static final String operateAffection="operate_affection";//
	public static final String power="power";//动力
	public static final String powerAffection="power_affection";//
	public static final String oil="oil";//
	public static final String oilAffection="oil_affection";//
	public static final String comfort="comfort";//舒适性
	public static final String comfortAffection="comfort_affection";//
	public static final String configure="configure";//配置
	public static final String configureAffection="configure_affection";//
	public static final String price="price";//价格
	public static final String priceAffection="price_affection";//
	public static final String quality="quality";//
	public static final String qualityAffection="quality_affection";//
	public static final String cost="cost";//性价比
	public static final String costAffection="cost_affection";//
	public static final String maintenance="maintenance";//维修保养
	public static final String maintenanceAffection="maintenance_affection";//维修保养
	public static final String attitude="attitude";//服务态度
	public static final String attitudeAffection="attitude_affection";//
	public static final String facility="facility";//配套设施
	public static final String facilityAffection="facility_affection";//
	public static final String stafflevel="stafflevel";//人员水平
	public static final String stafflevelAffection="stafflevel_affection";//
	public static final String pubTime="pub_time";//发布时间
}
